### ISSUE TITLE
Disk free or FileSystemUsage support

### ISSUE THREAD

**Issue by cvaldemar** [elastic/topbeat#11]
Hi,

Basic disk free/disk usage would be great to have provided by this beat, even if it not entirely fits under "top" functionality. Personally I think having another beat running on all machines would be overkill (Btw, I really of like how Bosun does it with all-in-one binary for their [scollector](https://github.com/bosun-monitor/scollector)).

I noticed @ruflin started a dfbeat project, which inspired me to [implement this functionality in topbeat](https://github.com/cvaldemar/topbeat/tree/with-fs). Example:

```json
{
    "count": 1,
    "fs.available": 26938,
    "fs.ctime": "2015-08-30T22:23:14.63556438+04:00",
    "fs.ffiles": 61930,
    "fs.files": 62248,
    "fs.mount": "/boot",
    "fs.total": 240972,
    "fs.used": 201593,
    "fs.used_p": 83.66,
    "shipper": "gnu",
    "timestamp": "2015-08-30T18:23:14.635Z",
    "type": "filesystem"
  }
```

However using GoSigar as datasource seems to leave out Windows support, which would be a nice thing to have.

Having a Cpu, Proc, Mem and Disk in a single beat would make it super easy and quick to get basic monitoring up running (I think those are the basic checks nagios provides for localhost as well).

What do you think?

**Comment by monicasarbu** [comment]
Hi,

I agree, it would be nice to have support for Disk usage as well in topbeat. Can you please send us a pull request with your changes?  I will try to add Windows support for Disk usage in elastic/gosigar.

**Comment by monicasarbu** [comment]
On windows, topbeat doesn't compile due to the following errors:

     ./sigar.go:269: undefined: syscall.Statfs_t
     ./sigar.go:270: undefined: syscall.Statfs

So, I changed topbeat to call the functions from gosigar library to get file system usage details.

**Comment by cvaldemar** [comment]
First, thanks for the merge!

Ah yes, my bad. I used the gosigars functions first, but my last commit moved the functionality to topbeat, looking back that shouldn't have been part of the merge :) Also, gosigar seems to calculate free blocks not bytes, so maybe we should add conversion to bytes (add available_b/used_b or _bytes fields).

**Comment by monicasarbu** [comment]
This is done now.
