### ISSUE TITLE
Update to rc1 gets field casting error

### ISSUE THREAD

**Issue by portante** [elastic/topbeat#110]
```
Error: Request to Elasticsearch failed: {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[xxpEly9LSom5TM6eKx6Gcg][packetbeat-2015.11.12][0]: RemoteTransportException[[gronk-gprfs004][inet[/172.17.40.4:9300]][indices:data/read/search[phase/query]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.SortedSetDVOrdinalsIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }]"}
```

I had shutdown all the hosts using topbeat and packetbeat, deleted all my indices, uploaded the new rc1 template, enabled the clients sending data, and then the new dashboards for rc1 via git clone of beats-dashboards, co origin/1.0.0-rc1 and running load.sh.

**Comment by ruflin** [comment]
@portante Which elasticsearch version are you using?

**Comment by portante** [comment]
@ruflin, 1.5

**Comment by ruflin** [comment]
Ok, so far we mainly tested with 1.7 and 2.0. It was working with rc4, right? Because the main change between the two is the addition of @timestamp: https://github.com/elastic/beats-dashboards/compare/1.0.0-beta4...1.0.0-rc1

**Comment by portante** [comment]
@ruflin, yes, it was working with beta4.  I must have done something wrong.  Will check later today.

**Comment by ruflin** [comment]
@portante The first thing that came to my mind when I saw the error message is that we change offset from int to long: https://github.com/elastic/filebeat/blob/master/etc/filebeat.template.json#L32 I have to check if the problem could be there. Didn't have the time yet to test it.

**Comment by portante** [comment]
@ruflin sorry for the false alarm!

This was a total pilot error on my part.  I ran the template installs against a localhost instance of elasticsearch I had running as a test environment instead of my production instance.

Sorry!

**Comment by ruflin** [comment]
@portante Good to hear it works now. The good news for me is that I now know that we are probably also compatible with elasticsearch 1.5 :-)
