### ISSUE TITLE
proc.cpu.user_p vs proc.cpu.total_p

### ISSUE THREAD

**Issue by andrewkroh** [elastic/topbeat#113]
The `proc.cpu.user_p` field should actually be `proc.cpu.total_p` because the calculation includes both the system time and user time.

Also what do you think about increasing the number of decimal places included in percentages beyond 2? Or would that be bad for some reason? I was thinking it would be nice to have a non-zero percentage even if it is small. It is not really possible to do a precise aggregation over the CPU percentage due to the rounding.

**Comment by monicasarbu** [comment]
@andrewkroh I checked the code in gosigar and from what I can see proc.cpu.user_p contains only the time spent in user space. Maybe I am missing something. What made you think that proc.cpu.user_p contains the time spent in kernel space?

**Comment by monicasarbu** [comment]
I checked the Topbeat code and `proc.cpu.user_p` is calculated based on the CPU time in user space and system space, so we need to rename it to `total_p`.

**Comment by monicasarbu** [comment]
Closing it in favor of https://github.com/elastic/beats/issues/631.
