### ISSUE TITLE
Track/Report IOPS and Disk Utilization %

### ISSUE THREAD

**Issue by skearns64** [elastic/topbeat#118]
Many server performance problems can be traced back to IO bottlenecks. It would be great if TopBeat were able to capture and report total IOPS, and disk utilization percentage. I suspect that the definition of IOPS is fairly clear. 

Disk utilization could have many meanings. The definition I prefer is in the top response here: http://serverfault.com/questions/9428/how-can-i-monitor-hard-disk-load-on-linux

To save a click: `iostat` does a good job here
 
```
% iostat -dx /dev/sda 5

Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
sda               0.78    11.03    1.19    2.82    72.98   111.07    45.80     0.13   32.78   1.60   0.64
```

> The disk utilisation is listed in the last column. This is defined as
> 
>> Percentage of CPU time during which I/O requests were issued to the device (band-width utilization for the device). Device saturation occurs when this value is close to 100%.

**Comment by ruflin** [comment]
@skearns64 We are currently thinking of a Metric/Sysbeat. This would probably more belong there to keep the focus of Topbeat on reporting top related things. I definitively agree that this is a required feature. It is good to have your reference for what your exact expectations are.

**Comment by skearns64** [comment]
@ruflin - thanks for taking a look! 

If we do build a metric/sysbeat, would the expectation be that an average user (someone interested in monitoring their infrastructure utilization) would run both Topbeat and Metric/Sysbeat on every machine/VM in their environment? I'm wondering whether there is more overhead from having two separate processes to configure/run/manage than the added value in separating them? 

I don't actually have an opinion here yet, just thinking out loud

**Comment by ruflin** [comment]
@skearns64 This is still under discussion. My view on this: Topbeat has two purposes: Monitoring top events and be a demo for a very simple beat that can be copied to create your own beat. So Topbeat for me he is here to stay. I see Sysbeat also having the topbeat features and many more which leads to be quite a bit complex. The idea is that Sysbeat will also be extendable so not everything has to be implemented inside the beat.

**Comment by monicasarbu** [comment]
@skearns64 Topbeat already gives you information about the disk utilization. 
![topbeat-dashboard2](https://cloud.githubusercontent.com/assets/11757159/11216937/38e2f55e-8d4e-11e5-8b30-f4897167f292.png)

**Comment by skearns64** [comment]
Thanks @monicasarbu , but in this case, I am not looking from the % disk space used, I am looking for the "disk activity" or disk active time%. I tried to define it above, but it's tricky! :)

**Comment by monicasarbu** [comment]
@skearns64 Yes, I meant that this would make sense to be in Topbeat as we have already disk related statistics.

**Comment by monicasarbu** [comment]
Closing in favor of https://github.com/elastic/beats/issues/422
