### ISSUE TITLE
init.d script incorrect for RC2

### ISSUE THREAD

**Issue by owulff** [elastic/topbeat#124]
Hi there

The init.d script still uses the old flag "-test".

You have to make the following update:
test_args="-e -configtest"

**Comment by ruflin** [comment]
@owulff Thanks for reporting. This was fixed with https://github.com/elastic/beats-packer/pull/25 I will keep the issue open until we can confirm that this fixed it as expected.

**Comment by owulff** [comment]
@ruflin Just downloaded RC2 from here: https://download.elastic.co/beats/topbeat/topbeat-1.0.0-rc2-x86_64.rpm

and figured it out.

**Comment by ruflin** [comment]
@owulff Yep, the issue was fixed after we uploaded the binary. We are currently in internal test of RC2. Somehow you already spotted the binary ;-)

**Comment by ruflin** [comment]
@owulff This should be resolved with GA. Please reopen if it still happens.
