### ISSUE TITLE
service message not accurate on debian

### ISSUE THREAD

**Issue by robin13** [elastic/topbeat#127]
When restarting service on debian I see:

```
Like the top command but outputing periodically to Elasticsearch. topbeat 
```
But topbeat has more outputs - e.g. to logstash. :)

**Comment by ruflin** [comment]
This should be adjusted here: https://github.com/elastic/beats-packer/blob/master/beats/topbeat.yml#L4

**Comment by robin13** [comment]
See PR: https://github.com/elastic/beats-packer/pull/26

**Comment by ruflin** [comment]
Thanks. Will merge it as soon as build is green (I don't think it will break it ;-) ).

**Comment by monicasarbu** [comment]
Merged. Thanks @robin13 for the fix.
