### ISSUE TITLE
Load / cores metric

### ISSUE THREAD

**Issue by robin13** [elastic/topbeat#128]
Knowing the load of a machine, or even the cpu time spent (percentage) is not very useful if you don't know the number of cores.  i.e. a load of 3.1 is still healthy if you have a 4-core machine, but very unhealthy if you have a 2-core machine.
Would it be possible to add another metric to the system messages indicating the value of ( load / cores ) ?

**Comment by monicasarbu** [comment]
In collectd, you can configure _ReportRelative_ option in Load plugin. If it's enabled, then the system load is divided by the number of available CPU cores, reported for intervals 1 min, 5 min and 15 min. Defaults to false.
https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_load

We can do something similar or just export another field containing the number of the CPU cores.

**Comment by robin13** [comment]
I think a configuration option to set that load / percentage CPU usage
should be "relative" rather than "absolute" would be easier to deal with
than another field, otherwise every visualisation in Kibana would require
scripted fields to calculate the result.

**Comment by christiangalsterer** [comment]
Also would be interested in seeing this added. I just had a quick view on the code (not really in detail) but it looks like that all necessary data are already there and "just" a new fields needs to be exported. What about cpu.user.relative_p?

**Comment by christiangalsterer** [comment]
Seems this is already addressed in #130, isn't it?

**Comment by christiangalsterer** [comment]
After checking more closely on #130 this is related but not the same thing. #130 creates an event for each CPU but not a field providing the total CPU usage divided by the number of cores.

**Comment by monicasarbu** [comment]
@robin13 Yes, you are right. I'll just export additional fields: load1_rel, load5_rel and load15_rel (the naming to be discussed). We need to be able to enable exporting them in the configuration file. By default these fields should not be export. The load info is available only on unix systems.

@christiangalsterer yes, #130 is a bit different than this.

**Comment by monicasarbu** [comment]
Closing in favor of https://github.com/elastic/beats/issues/420

**Comment by robin13** [comment]
Hey @monicasarbu, maybe a false-click, but now both this and the referred issue are closed... maybe reopen one?

**Comment by monicasarbu** [comment]
@robin13 We merged today all the Beats into one repo: https://github.com/elastic/beats and I copied this issue to https://github.com/elastic/beats/issues/420.
