### ISSUE TITLE
Add a note, about topbeat beeing in the beats repository, to the getting started page

### ISSUE THREAD

**Issue by jakommo** [elastic/topbeat#135]
The [getting started page](https://github.com/elastic/topbeat/blob/master/docs/gettingstarted.asciidoc) only talks about installing topbeat from a file, while it is also available in the [beats repo](https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html).

In my opinion it would be a good thing to point users to that option as well.  Especially as it is more easy to stay up to date with a repository, than it is with a manual package install.

**Comment by dedemorton** [comment]
@elastic/beats I'm curious to hear your thoughts on this request.

**Comment by ruflin** [comment]
+1 one also pointing the the repositories in the getting started guide.
