### ISSUE TITLE
Missing index-pattern-field

### ISSUE THREAD

**Issue by EdHanBTO** [elastic/topbeat#137]
Hi

Perhaps not a technical issue but am receiving the message 'Could not locate that index-pattern-field (id: beat.name)' on the sample TopBeat dashboard. Valid topbeat data is being received:

@timestamp:November 24th 2015, 09:46:50.250 count:1 fs.device_name:sysfs fs.total:0 fs.used:0 fs.used_p:0% fs.free:0 fs.avail:0 fs.files:0 fs.free_files:0 fs.mount_point:/sys shipper:elksvr01 tags:beat, web-tier type:filesystem @version:1 _id:AVE4430u046YvIKjTpD4 _type:filesystem _index:topbeat-2015.11.24 _score:

Everything was working before updating the plugins, could anyone provide a pointer where to start troubleshooting to get valid data into beat.name please?

Regards

Ed

**Comment by monicasarbu** [comment]
Starting with 1.0.0-RC2, Topbeat exports beat.name instead of shipper, so you need to use the latest version of the beats dashboards (1.0.0-RC2) in order to work with the latest Topbeat version.

**Comment by EdHanBTO** [comment]
Most kind, would also explain another logstash issue so thank you very much !

Kind Regards

Ed
