### ISSUE TITLE
Installing topbeat-service on windows-machines if there are spaces in $workdir

### ISSUE THREAD

**Issue by Svenfa** [elastic/topbeat#142]
Hi everyone, this is my first issue, please correct me if something is wrong.

The script to install topbeat as windows-service 'install-service-topbeat.ps1' inside the [topbeat for windows package](https://download.elastic.co/beats/topbeat/topbeat-1.0.0-windows.zip) does not install the topbeat-service correctly. The service won't start if the "$workdir" path contains spaces.

Please fix the "-binaryPathName" line by adding quotes:

Original:
>-binaryPathName "$workdir\\topbeat.exe -c $workdir\\topbeat.ym"

Fixed by escaping the quotes with `:

>-binaryPathName "\`"$workdir\\topbeat.exe\`" -c \`"$workdir\\topbeat.yml\`""

**Comment by andrewkroh** [comment]
Hi @Svenfa, thanks for reporting. Could you possibly open a pull request for this? The file is [here](https://github.com/elastic/beats-packer/blob/master/platforms/windows/install-service.ps1.j2). It is used by all the beats.

**Comment by Svenfa** [comment]
Hi @andrewkroh, thanks for the hint. Since I'm not a dev and never did anything on github so far, I hope that the pull request ist created correctly.

**Comment by ruflin** [comment]
For referecence, PR can be found here: https://github.com/elastic/beats-packer/pull/32
