### ISSUE TITLE
Add cpu.idle_p and cpu.iowait_p (for system stats)

### ISSUE THREAD

**Issue by Qtax** [elastic/topbeat#145]
For system stats it would be nice to have `cpu.idle_p` and `cpu.iowait_p` (as in the top header) so that you could easily see the total system usage (`1-idle_p`), and have clearer stats of IO bottlenecks.

At the moment I'm using an inline script that does `system_p + user_p`, but it would be nicer to use `idle_p` if it available.

The `cpu.idle` and `cpu.iowait` just contain huge numbers that always keep growing (as do `cpu.system`, `cpu.user`, etc), and I'm not sure what to do with those or how to use them in any meaningful way. Shouldn't those be deltas? Is this by design? (Couldn't find any mention of what these numbers are or what they should be in the docs.)

**Comment by monicasarbu** [comment]
@qtax On linux the cpu.idle, cpu.iowait, cpu.system and cpu.user is read from /proc/stat. They identify the amount of time the CPU has spent performing different kinds of work. I agree with you that they contain these huge numbers that are not very useful for the user. I think it makes more sense to be replaced by percentages.

**Comment by monicasarbu** [comment]
Closing in favor of https://github.com/elastic/beats/issues/423
