### ISSUE TITLE
Cleanup cpu usage fields (system wide)

### ISSUE THREAD

**Issue by monicasarbu** [elastic/topbeat#146]
Currently we export the following fields:
#cpu.idle	  	42,093,003
#cpu.iowait	  	0
#cpu.irq	  	0
#cpu.nice	  	0
#cpu.softirq	  	0
#cpu.steal	  	0
#cpu.system	  	3,484,300
#cpu.system_p	  	22%
#cpu.user	  	5,094,559
#cpu.user_p	  	74%

For the user these huge numbers don't mean much, so I suggest to be replaced by percentages and
export in the end the following:

- cpu.user_p
- cpu.system_p
- cpu.idle_p
- cpu.iowait_p

This change can be done in the next major release as it removes fields.

**Comment by ruflin** [comment]
I like the suggestion to focus on the four fields you mentioned above by default. Would it be possible to make the other fields still accessible through for example a "extended" flag? It would also be interesting to hear feedback from @drewr and his team on what the most relevant values for them are?

**Comment by monicasarbu** [comment]
@ruflin yes, the idea is to export the *_p values by default and have another option in Topbeat to enable/disable the rest.

**Comment by monicasarbu** [comment]
Closing in favor of https://github.com/elastic/beats/issues/421
