### ISSUE TITLE
Disk IO stats

### ISSUE THREAD

**Issue by Qtax** [elastic/topbeat#147]
Would be great if topbeat also reported disk utilization, the percentage of time the device is used, not the space used on it. On linux it's the `%util` column of `iostat -d -x`. `nmon` (then `d`) also reports this nicely. The bandwidth read/written could also be useful, also reported by the same command.

`iostat -d -x`, the `%util` column:
![iostat -d -x](http://i.imgur.com/YfCzxMY.png)

`nmon` - `d`, the `Busy` column:
![nmon](http://i.imgur.com/5QMKa25.png)

Disk utilization is the only metric I really miss in topbeat for a complete overview of our servers health.

**Comment by monicasarbu** [comment]
Requested also by #/118

**Comment by monicasarbu** [comment]
Closing in favor of https://github.com/elastic/beats/issues/422
