### ISSUE TITLE
Build fails on FreeBSD 

### ISSUE THREAD

**Issue by jalaluddeen** [elastic/topbeat#153]
getting this error when I run go get -t ./...

# github.com/elastic/beats/filebeat/harvester
harvester/encoding.go:23: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
	utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
		have NewDecoder() transform.Transformer
		want NewDecoder() *encoding.Decoder
harvester/encoding.go:24: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
	utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
		have NewDecoder() transform.Transformer
		want NewDecoder() *encoding.Decoder
harvester/encoding.go:25: cannot use utf8Encoding literal (type utf8Encoding) as type encoding.Encoding in map value:
	utf8Encoding does not implement encoding.Encoding (wrong type for NewDecoder method)
		have NewDecoder() transform.Transformer
		want NewDecoder() *encoding.Decoder

**Comment by ruflin** [comment]
Quite a bit of work has gone into freebsd compatibility. For more details have a look here: https://github.com/elastic/beats/issues/1034 Closing this one.
