### ISSUE TITLE
Support for Windows counters 

### ISSUE THREAD

**Issue by elvarb** [elastic/topbeat#28]
It would be very useful if Topbeat could access all the counters that windows has to offer. 

They can be viewed using powershell

**Comment by elvarb** [comment]
Powershell 

    Get-Counter -ListSet *

Or use perfmon to view the available counters

**Comment by fenneh** [comment]
+1 for this - Already having to run multiple monitoring agents, if this was supported then quite a few could be purged from my environments.

**Comment by BasiliusCarver** [comment]
+1
A lot of those custom counters can come in very useful, e.g. SQL Server:Locks "Average Wait Time (ms)"

If you're periodically firing up powershell to check those counters there can be a pretty noticeable CPU hit, perfmon seems to be a lighter option.
I noticed the powershell overhead when performance testing Splunk data collection and found this in reference to it:
https://powertoe.wordpress.com/2012/06/27/how-to-execute-powershell-scripts-without-the-cpu-hit-to-start-powershell/

**Comment by kimchy** [comment]
this to me sounds like a great feature, but either on its own dedicated beat, or in metrics beat.

**Comment by monicasarbu** [comment]
Close in favor of https://github.com/elastic/beats/issues/507
