### ISSUE TITLE
Update documentation to use new index

### ISSUE THREAD

**Issue by monicasarbu** [elastic/topbeat#30]
In the doc, the index topbeat-* needs to be replaced by [topbeat-]YYYY.MM.DD. Also, the screenshots need to be updated.

**Comment by monicasarbu** [comment]
Done in the beta3 branch.

**Comment by ruflin** [comment]
Closing as done in https://github.com/monicasarbu/topbeat/commit/f447ce58e53795be058e872589d57d1c65d75ebb
