### ISSUE TITLE
status 400: Field name [proc.cpu] cannot contain '.'

### ISSUE THREAD

**Issue by imreACTmd** [elastic/topbeat#50]
I'm trying topbeat 1.03 with ES2.0beta1 and I get status 400:

reason: Field name [proc.cpu] cannot contain '.'

**Comment by imreACTmd** [comment]
It was a design decision apparently:

https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_mapping_changes.html#_field_names_may_not_contain_dots

**Comment by andrewkroh** [comment]
Duplicate #44
