### ISSUE TITLE
Per-process collection doesn't work in Elasticsearch 2.0 Beta2

### ISSUE THREAD

**Issue by schmorgs** [elastic/topbeat#51]
Topbeat is storing filesystem and system level metrics, but not storing  per-process stats.  If I run in debug, I can see it's collecting the process stats, but is not indexing them.

If I take one of the process documents from the debug output, and try to post it through curl, I get this : 
```
curl -XPOST localhost:9200/topbeat-2015.09.29/proc -d '
{"count":1,"proc.cpu":{"user":129790,"user_p":3.09,"system":28010,"total":157800,"start_time":"08:29"},"proc.mem":{"size":4575424,"rss":887024,"rss_p":11.98,"share":19592},"proc.name":"java","proc.pid":7273,"proc.ppid":1,"proc.state":"sleeping","shipper":"myhost","timestamp":"2015-09-29T08:22:06.476Z","type":"proc"}
'
```

Gives this message : 
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [proc.cpu] cannot contain '.'"}],"type":"mapper_parsing_exception","reason":"Field name [proc.cpu] cannot contain '.'"},"status":400}
```

I've read about the more strict mapping enforcement in Elastic 2.0, and looks like it might be related but can't tell for sure.

**Comment by easyrasta** [comment]
Duplicate #44

**Comment by monicasarbu** [comment]
This is fixed already in master and the fix will be available in the beta4 release.
