### ISSUE TITLE
Uptime

### ISSUE THREAD

**Issue by claygorman** [elastic/topbeat#74]
The docs say start_time under cpu is posted (i assume this is system uptime) but I do not see it in the body of the packets. I am using beta4 which seems to be in sync with master branch at this time.

Anyone else able to replicate?

**Comment by ruflin** [comment]
@claygorman I assume you are talking about proc.cpu.start_time: https://www.elastic.co/guide/en/beats/topbeat/current/exported-fields.html#_proc_cpu_start_time This is the start_time when the process was started. 

Which operating system are you using? Can you post one of the json outputs here?

**Comment by claygorman** [comment]
I seem to have made a mistake here and I apologize. Under proc I do actually see the start_time key, I was looking under type:"system" events.

I was originally looking for server uptime but I think I can just take the oldest proc time or look for something like "/sbin/init" and get its start_time.

**Comment by ruflin** [comment]
@claygorman Good to hear the data is there. If you think it would make sense to have the uptime also reported separately, feel free to open an issue with this feature request.
