### ISSUE TITLE
Add shipper.raw by default in EL mapping

### ISSUE THREAD

**Issue by easyrasta** [elastic/topbeat#82]
Would be great to have a shipper.raw in default mapping for topbeat

**Comment by monicasarbu** [comment]
If you load the template in Elasticsearch, then shipper is not analyzed anymore. To load the template, you just need to follow the steps from our Getting started guide:
https://www.elastic.co/guide/en/beats/topbeat/current/topbeat-getting-started.html#topbeat-template

Does this solves your problem?

**Comment by easyrasta** [comment]
yes sorry. Thank you.
